### ISSUE TITLE
ECONNREFUSED on development server launch

### ISSUE THREAD

**Issue by JGarnerDev** [JGarnerDev/UFOCAN#4]
![gyukifyuf](https://user-images.githubusercontent.com/1173827/87834164-be619e80-c857-11ea-8f6d-11f9c2f099eb.png)

As shown above, there is an issue with a collaborator being unable to run the server, as it is attempting to reach port 3306 where it should be port 5000.

**Comment by migueog** [comment]
I see that the port number can be either what is defined by the process.env value or 5000. 

Have you tried only broadcasting to port 5000?

**Comment by JGarnerDev** [comment]
As the console writes out, the server is indeed being casted at port 5000. The problem @KellanSelig is having is that somehow, locally, the application is expecting the port to be 3306 instead. This could be due to an incomplete installation of modules and libraries (as he is fairly new to web development in this context), that somehow the package.json file has made explicit to fall back on port 3306, or that (most likely) our process.env wasn't put into the 'server' directory in this case.

**Comment by KellanSelig** [comment]
Victory!
